# Generated by Django 3.2.18 on 2023-03-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arithmeticalconceptmodel_numbermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arithmeticalconceptmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hidden_arith_concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.arithmeticalconceptmodel')),
                ('possible_ariths', models.ManyToManyField(blank=True, related_name='_core_gamemodel_possible_ariths_+', to='core.ArithmeticalConceptModel')),
                ('possible_numbers', models.ManyToManyField(blank=True, related_name='_core_gamemodel_possible_numbers_+', to='core.NumberModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
