# Generated by Django 3.2.18 on 2023-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gamemovemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_state',
            field=models.CharField(default='Runing...', max_length=10),
        ),
    ]
